# Generated by Django 4.0.2 on 2022-02-12 15:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.TextField(choices=[('Dissertação', 'Dissertacao'), ('Artigo de Opinião', 'Artigo De Opiniao'), ('Carta Aberta', 'Carta Aberta'), ('Resenha', 'Resenha'), ('Crõnica Reflexiva', 'Cronica Reflexiva'), ('Narração', 'Narracao'), ('Descrição', 'Descricao'), ('Estilo Jornalístico', 'Jornalistico'), ('Comentário', 'Comentario')], max_length=30)),
                ('tema', models.CharField(max_length=100)),
                ('vestibular', models.TextField(blank=True, choices=[('ENEM', 'Enem'), ('Unicamp', 'Unicamp'), ('Fuvest', 'Fuvest'), ('Unesp', 'Unesp'), ('UERJ', 'Uerj'), ('Outros', 'Outros')], max_length=15, null=True)),
                ('data_realizacao', models.DateField(default=datetime.datetime.today)),
                ('nota', models.IntegerField(blank=True, null=True)),
                ('correcao', models.CharField(blank=True, max_length=400, null=True)),
                ('tempo_de_realizacao', models.IntegerField()),
                ('data_da_correcao', models.DateField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
