# Generated by Django 4.0.2 on 2022-02-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erros_e_acertos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='descricao_erros',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
