# Generated by Django 4.0.2 on 2022-02-06 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erros_e_acertos', '0002_alter_lista_descricao_erros'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
