# Generated by Django 4.0.2 on 2022-02-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erros_e_acertos', '0003_lista_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='data_revisao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
